"""initial schema

Revision ID: 7b867b93631e
Revises: 
Create Date: 2026-09-08 10:40:12.918357+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '7b867b93631e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_emails', sa.JSON(), nullable=False),
    sa.Column('calendar_recipient_emails', sa.JSON(), nullable=False),
    sa.Column('teams_webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('notify_daily_when_expired', sa.Boolean(), nullable=False),
    sa.Column('warn_days', sa.Integer(), nullable=False),
    sa.Column('critical_days', sa.Integer(), nullable=False),
    sa.Column('contact_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target'), ['target'], unique=False)

    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'MANUAL', name='certsource'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('subject_cn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_rfc4514', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer_rfc4514', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serial_decimal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('fingerprint_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sans', sa.JSON(), nullable=False),
    sa.Column('key_algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('pem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='certstatus'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('extra_recipients', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_fingerprint_sha256'), ['fingerprint_sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificate_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_not_after'), ['not_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_verified'), ['verified'], unique=False)

    op.create_table('job_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificates_checked', sa.Integer(), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EXPIRY', 'RENEW', name='invitekind'), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('REQUEST', 'CANCEL', name='invitemethod'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ERROR', 'SKIPPED', name='deliverystatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cert_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_id', 'kind', name='uq_invite_kind')
    )
    with op.batch_alter_table('calendar_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_invite_cert_id'), ['cert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_invite_uid'), ['uid'], unique=False)

    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'TEAMS', name='channel'), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ERROR', 'SKIPPED', name='deliverystatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cert_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_id', 'channel', 'dedupe_key', name='uq_notification_once')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_cert_id'), ['cert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_status'))
        batch_op.drop_index(batch_op.f('ix_notification_log_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_notification_log_channel'))
        batch_op.drop_index(batch_op.f('ix_notification_log_cert_id'))

    op.drop_table('notification_log')
    with op.batch_alter_table('calendar_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_invite_uid'))
        batch_op.drop_index(batch_op.f('ix_calendar_invite_cert_id'))

    op.drop_table('calendar_invite')
    op.drop_table('job_run')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_verified'))
        batch_op.drop_index(batch_op.f('ix_certificate_superseded_by_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_status'))
        batch_op.drop_index(batch_op.f('ix_certificate_source'))
        batch_op.drop_index(batch_op.f('ix_certificate_not_after'))
        batch_op.drop_index(batch_op.f('ix_certificate_label'))
        batch_op.drop_index(batch_op.f('ix_certificate_fingerprint_sha256'))
        batch_op.drop_index(batch_op.f('ix_certificate_environment'))

    op.drop_table('certificate')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_email'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
